// <auto-generated />
namespace OffRoad.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Evenement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Evenement));
        
        string IMigrationMetadata.Id
        {
            get { return "201511181521283_Evenement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
