// <auto-generated />
namespace OffRoad.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Userrequierdnom_prenom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Userrequierdnom_prenom));
        
        string IMigrationMetadata.Id
        {
            get { return "201510281424490_User -requierd nom_prenom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
